/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorPretRouteImport } from './routes/calculator-pret'
import { Route as GhidProprietarTerasaRouteImport } from './routes/ghid-proprietar-terasa'
import { Route as HidroizolatiiTeraseCirculabileRouteImport } from './routes/hidroizolatii-terase-circulabile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorPretRoute = CalculatorPretRouteImport.update({
  id: '/calculator-pret',
  path: '/calculator-pret',
  getParentRoute: () => rootRouteImport,
} as any)
const GhidProprietarTerasaRoute = GhidProprietarTerasaRouteImport.update({
  id: '/ghid-proprietar-terasa',
  path: '/ghid-proprietar-terasa',
  getParentRoute: () => rootRouteImport,
} as any)
const HidroizolatiiTeraseCirculabileRoute =
  HidroizolatiiTeraseCirculabileRouteImport.update({
    id: '/hidroizolatii-terase-circulabile',
    path: '/hidroizolatii-terase-circulabile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator-pret': typeof CalculatorPretRoute
  '/ghid-proprietar-terasa': typeof GhidProprietarTerasaRoute
  '/hidroizolatii-terase-circulabile': typeof HidroizolatiiTeraseCirculabileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator-pret': typeof CalculatorPretRoute
  '/ghid-proprietar-terasa': typeof GhidProprietarTerasaRoute
  '/hidroizolatii-terase-circulabile': typeof HidroizolatiiTeraseCirculabileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator-pret': typeof CalculatorPretRoute
  '/ghid-proprietar-terasa': typeof GhidProprietarTerasaRoute
  '/hidroizolatii-terase-circulabile': typeof HidroizolatiiTeraseCirculabileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator-pret'
    | '/ghid-proprietar-terasa'
    | '/hidroizolatii-terase-circulabile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator-pret'
    | '/ghid-proprietar-terasa'
    | '/hidroizolatii-terase-circulabile'
  id:
    | '__root__'
    | '/'
    | '/calculator-pret'
    | '/ghid-proprietar-terasa'
    | '/hidroizolatii-terase-circulabile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorPretRoute: typeof CalculatorPretRoute
  GhidProprietarTerasaRoute: typeof GhidProprietarTerasaRoute
  HidroizolatiiTeraseCirculabileRoute: typeof HidroizolatiiTeraseCirculabileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator-pret': {
      id: '/calculator-pret'
      path: '/calculator-pret'
      fullPath: '/calculator-pret'
      preLoaderRoute: typeof CalculatorPretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghid-proprietar-terasa': {
      id: '/ghid-proprietar-terasa'
      path: '/ghid-proprietar-terasa'
      fullPath: '/ghid-proprietar-terasa'
      preLoaderRoute: typeof GhidProprietarTerasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidroizolatii-terase-circulabile': {
      id: '/hidroizolatii-terase-circulabile'
      path: '/hidroizolatii-terase-circulabile'
      fullPath: '/hidroizolatii-terase-circulabile'
      preLoaderRoute: typeof HidroizolatiiTeraseCirculabileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorPretRoute: CalculatorPretRoute,
  GhidProprietarTerasaRoute: GhidProprietarTerasaRoute,
  HidroizolatiiTeraseCirculabileRoute: HidroizolatiiTeraseCirculabileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
